environment:
    test: .myshoplinestg.com
    pre: .preview.myshopline.com
    pro: .myshopline.com


handle:
    test: niki03
    pre: niki-us
    pro: niki-us

database:
    host:
    port:
    user:
    password:

header:
    cookie: '_BEAMER_USER_ID_whBStDUm30458=b99b65e5-1186-4c59-933d-f8e9e5f6f984; _BEAMER_FIRST_VISIT_whBStDUm30458=2023-02-01T06:40:35.843Z; _BEAMER_FIRST_VISIT_undefined=2023-02-06T06:09:10.546Z; a_ste=krobHo7p7fCJvjzWRX1BOkSVlhbzy2vzP3Mi/2cGOVy01UjUVhSQaMCYXlAAsFoNb8aFMObih5h5l/EAByfhmg==; r_b_ined=1; a_osudb_appid=1163336839; a_osudb_subappid=1; a_lang=zh-hant-tw; googtrans=/auto/en; a_osudb_csrf=#C01#SID0000073BEvf9/DitqUjAT0NSBrnXutxzZ5zIIFhgMyFUQaFhqt8xoEAQybylYyfEoOsMZirsmotO+xGsUe7kNMAfl1eRfB0MEnnhwszjUoztGSfxbye2fM4+gk5tcV52xIqirTAULSkKFVKFQYr/09lszfw+mjkusIKNY2RspDyJHI7kdon; a_cstgc=1163336839_1_4211387386_168345663941847VSHa; a_osudb_uid=4211387386; a_osudb_oar=#01#SID0000073BIWZtFtDL3dn4zqPZYEU92V10mDl7wa46c2KoACTKZveSXcJ3vZQI2KNh7EqABC5YbX6NkaUnLLZjujuHptXF1GOCFZWyNqLlCUe6SfpxmsLTicSGYNmVSOZPvubJ+gGZe7g+Hlny+k9/xiFae/CJw==; a_lce=1684061439514; _BEAMER_FILTER_BY_URL_whBStDUm30458=false; a_dhch=niki03; r_b_in=1'


filePath:
    discountCodePath: testData/DiscountCodeActivity.json
    preCasePath: testData/preCase.json
























